# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchFromGitHub,
}: {
  rose-pine-wezterm = {
    pname = "rose-pine-wezterm";
    version = "d3c635c7bbfc8cea33f8f50322ac7a88cb85f3ca";
    src = fetchFromGitHub {
      owner = "x0ba";
      repo = "wezterm";
      rev = "d3c635c7bbfc8cea33f8f50322ac7a88cb85f3ca";
      fetchSubmodules = false;
      sha256 = "sha256-RYAx4gDQ0TJB3d04q1QrtybJSgc/addqTrfMHXu+tU0=";
    };
    date = "2024-06-25";
  };
}
