{ lib, config, ... }:
{

  options = {
    ghostty.enable = lib.mkEnableOption "enables ghostty";
  };

  config = lib.mkIf config.ghostty.enable {
    programs.ghostty = {
      enable = true;

      settings = {
        mouse-hide-while-typing = true;
        unfocused-split-opacity = 0.8;

        quit-after-last-window-closed = true;
        macos-titlebar-style = "tabs";
        window-save-state = "never";

        cursor-style = "bar";
        window-padding-color = "extend";

        macos-option-as-alt = true;
        clipboard-read = "allow";
        clipboard-paste-protection = false;
        confirm-close-surface = false;

        font-family = "Berkeley Mono";
        font-size = 13;

        # theme = "catppuccin-mocha";

        window-padding-x = 10;
        window-height = 30;
        window-width = 120;
      };

      extraConfig = ''
        # Scheme: Oxocarbon Dark
        # Generated by Ghostty Base16 Converter
        background = 161616
        foreground = f2f4f8

        selection-background = 393939
        selection-foreground = 161616

        palette = 0=#161616
        palette = 1=#3ddbd9
        palette = 2=#33b1ff
        palette = 3=#ee5396
        palette = 4=#42be65
        palette = 5=#be95ff
        palette = 6=#ff7eb6
        palette = 7=#f2f4f8
        palette = 8=#525252
        palette = 9=#3ddbd9
        palette = 10=#33b1ff
        palette = 11=#ee5396
        palette = 12=#42be65
        palette = 13=#be95ff
        palette = 14=#ff7eb6
        palette = 15=#08bdba
        palette = 16=#78a9ff
        palette = 17=#82cfff
        palette = 18=#262626
        palette = 19=#393939
        palette = 20=#dde1e6
        palette = 21=#ffffff
      '';

      keybindings = {
        "super+left" = "goto_split:left";
        "super+right" = "goto_split:right";
        "super+up" = "goto_split:top";
        "super+down" = "goto_split:bottom";

        "super+control+left" = "resize_split:left,40";
        "super+control+right" = "resize_split:right,40";
        "super+control+up" = "resize_split:up,40";
        "super+control+down" = "resize_split:down,40";

        "page_up" = "scroll_page_fractional:-0.5";
        "page_down" = "scroll_page_fractional:0.5";
      };
    };
  };
}
