# Mountain Theme

[colors]
foreground = "#f0f0f0"
background = "#0f0f0f"
cursor_bg = "#ac8aac"
cursor_fg = "#0f0f0f"
cursor_border = "#262626"
split = "#4c4c4c"

ansi = [ "#262626", "#ac8a8c", "#8aac8b", "#aca98a", "#8f8aac", "#ac8aac","#8aabac", "#e7e7e7" ]
brights = [ "#4c4c4c", "#c49ea0", "#9ec49f", "#c4c19e", "#a39ec4", "#c49ec4", "#9ec3c4", "#f5f5f5" ]

[colors.tab_bar]
background = "#0f0f0f"

[colors.tab_bar.active_tab]
bg_color = '#8f8aac'
fg_color = '#0f0f0f'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = "#0f0f0f"
fg_color = '#f0f0f0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#0f0f0f'
fg_color = '#f0f0f0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
name = 'Mountain'
