[colors]
background = '#0c0e0f'
foreground = '#edeff0'
cursor_bg = '#edeff0'
cursor_border = '#232526'
cursor_fg = '#0c0e0f'

ansi = [
    "#232526",
    "#df5b61",
    "#78b892",
    "#de8f78",
    "#6791c9",
    "#bc83e3",
    "#67afc1",
    "#e4e6e7",
]
brights = [
    "#2c2e2f",
    "#e8646a",
    "#81c19b",
    "#e79881",
    "#709ad2",
    "#c58cec",
    "#70b8ca",
    "#f2f4f5",
]

[colors.tab_bar]
background = "#090909"

[colors.tab_bar.active_tab]
bg_color = '#6791c9'
fg_color = '#edeff0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = "#090909"
fg_color = '#edeff0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#090909'
fg_color = '#edeff0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
name = 'Yoru'
