[colors]
background = '#101317'
foreground = '#d4d4d5'
cursor_bg = '#8AB0DF'
cursor_border = '#7AB0DF'
cursor_fg = '#101317'

ansi = [
    '#171C21',
    '#F87070',
    '#79DCAA',
    '#FFE59E',
    '#7AB0DF',
    '#C397D8',
    '#70C0BA',
    '#D4D4D5',
]
brights = [
    '#171C21',
    '#fa6969',
    '#36C692',
    '#FFCE66',
    '#7AB0DF',
    '#B77EE0',
    '#54CED6',
    '#e0e0e0',
]

[colors.tab_bar]
background = "#101317"

[colors.tab_bar.active_tab]
bg_color = '#7ab0df'
fg_color = '#101317'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = "#101317"
fg_color = '#d4d4d5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#101317'
fg_color = '#f4f4f4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
name = 'Radium'
